### ISSUE TITLE
grid on the example link is not working

### ISSUE THREAD

**Issue by AtesDANIS** [DevExpress-Examples/how-to-implement-an-editable-aspxpivotgrid-e1949#1]
https://codecentral.devexpress.com/e1949 page has problems

**Comment by AleksandrKostik** [comment]
Thank you for your report. We are currently examining this misbehavior in greater detail. As an immediate solution, download the example source code and run it locally.

**Comment by MikhailTymchukDX** [comment]
Fixed.
